/* knock_filter.h -- PLACEHOLDER (pass-through coefficients).
 * Replace this file by the knock_filter.h generated by YOUR
 * filterdesign.c (Exercise 10.2) before using the sketch.
 */
#ifndef KNOCK_FILTER_H
#define KNOCK_FILTER_H
#include <stdint.h>

#define KF_FS_HZ 25000
#define KF_FIR_N 1
#define KF_NSEC 1

static const float kf_fir[KF_FIR_N] = { 1.0f };
static const int16_t kf_fir_q15[KF_FIR_N] = { 32767 };
static const float kf_sos[KF_NSEC][5] = { { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f } };
static const int16_t kf_sos_q14[KF_NSEC][5] = { { 16384, 0, 0, 0, 0 } };
static const float kf_bp2[5] = { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f };
static const int16_t kf_bp2_q14[5] = { 16384, 0, 0, 0, 0 };

#endif /* KNOCK_FILTER_H */
