/*
 * Sheet 10 -- Exercise 10.2: filter design tool (student template)
 *
 * Build and run:   gcc -O2 -o filterdesign filterdesign.c -lm
 *                  ./filterdesign            (writes knock_filter.h)
 * (filtdesign.h, asciiplot.h in the same directory)
 *
 * Designs the knock band-pass of Exercise 10.1
 *   fs = 25 kHz, pass band 6.0..7.0 kHz (max. 1 dB loss),
 *   stop bands <= 5.0 kHz and >= 8.0 kHz (min. 40 dB attenuation)
 * as a linear-phase FIR filter (window method) and as an IIR Butterworth
 * band-pass (bilinear transform, biquad cascade), checks the specification,
 * and exports the coefficients as C header (float, Q15 / Q14) for the
 * Wokwi sketches of Sheets 10 and 12.
 */
#include <stdio.h>
#include <stdint.h>
#include <math.h>
#include "filtdesign.h"
#include "asciiplot.h"

#define FS    25000.0
#define FP1    6000.0     /* pass band          */
#define FP2    7000.0
#define FST1   5000.0     /* stop-band edges    */
#define FST2   8000.0
#define AP        1.0     /* dB                 */
#define AS       40.0     /* dB                 */
#define FIR_N    83       /* chosen FIR length (Hamming, see 10.1) */
#define F0     6500.0     /* centre (knock mode 1) */
#define BW2     400.0     /* bandwidth of the single biquad (matched to tau) */
#define NF      500       /* frequency grid for plots */

/* worst-case pass-band loss and stop-band gain (dB) of a response given
   by a callback-free approach: we evaluate FIR or SOS explicitly */
static void check_fir(const double *h, int N, double *pass_min, double *pass_max,
                      double *stop_max)
{
    int i;
    *pass_min = 1e9; *pass_max = -1e9; *stop_max = -1e9;
    for (i = 0; i <= 500; i++) {
        double f = 0.5 * FS * i / 500.0, m = fd_db(c_abs(fd_fir_resp(h, N, f, FS)));
        if (f >= FP1 && f <= FP2) { if (m < *pass_min) *pass_min = m; if (m > *pass_max) *pass_max = m; }
        if (f <= FST1 || f >= FST2) { if (m > *stop_max) *stop_max = m; }
    }
}

static void check_sos(const biquad_t *s, int ns, double *pass_min, double *pass_max,
                      double *stop_max)
{
    int i;
    *pass_min = 1e9; *pass_max = -1e9; *stop_max = -1e9;
    for (i = 0; i <= 500; i++) {
        double f = 0.5 * FS * i / 500.0, m = fd_db(c_abs(fd_sos_resp(s, ns, f, FS)));
        if (f >= FP1 && f <= FP2) { if (m < *pass_min) *pass_min = m; if (m > *pass_max) *pass_max = m; }
        if (f <= FST1 || f >= FST2) { if (m > *stop_max) *stop_max = m; }
    }
}

/* TODO (d): convert x to a 16-bit integer in Q15 (x * 2^15) resp.
   Q2.14 (x * 2^14) with rounding and saturation to -32768..32767 */
static int q15(double x)
{
    (void)x;
    return 0;
}
static int q14(double x)
{
    (void)x;
    return 0;
}

static void write_biquad(FILE *f, const biquad_t *s, int last, int fixed)
{
    if (fixed)
        fprintf(f, "    { %6d, %6d, %6d, %6d, %6d }%s\n", q14(s->b[0]), q14(s->b[1]),
                q14(s->b[2]), q14(s->a[1]), q14(s->a[2]), last ? "" : ",");
    else
        fprintf(f, "    { %.9ef, %.9ef, %.9ef, %.9ef, %.9ef }%s\n", s->b[0], s->b[1],
                s->b[2], s->a[1], s->a[2], last ? "" : ",");
}

static int export_header(const char *path, const double *h, int N, const biquad_t *sos,
                         int ns, const biquad_t *bp2)
{
    FILE *f = fopen(path, "w");
    int n, k;
    if (!f) { perror(path); return -1; }
    fprintf(f, "/* %s -- generated by filterdesign.c (Sheet 10). Do not edit.\n", path);
    fprintf(f, " * Knock band-pass, fs = %.0f Hz, pass band %.0f..%.0f Hz (%.1f dB),\n", FS, FP1, FP2, AP);
    fprintf(f, " * stop bands <= %.0f Hz and >= %.0f Hz (%.0f dB).\n *\n", FST1, FST2, AS);
    fprintf(f, " * kf_fir[]      FIR, Hamming window, linear phase, delay (N-1)/2 samples\n");
    fprintf(f, " * kf_fir_q15[]  same in Q15 (value = c * 2^15)\n");
    fprintf(f, " * kf_sos[][5]   Butterworth band-pass as biquad cascade,\n");
    fprintf(f, " *               rows {b0, b1, b2, a1, a2}, a0 = 1:\n");
    fprintf(f, " *               H_k(z) = (b0 + b1 z^-1 + b2 z^-2)/(1 + a1 z^-1 + a2 z^-2)\n");
    fprintf(f, " * kf_sos_q14    same in Q2.14 (value = c * 2^14), because |a1| < 2;\n");
    fprintf(f, " *               use with Q15 data: acc(Q29) >> 14 -> Q15\n");
    fprintf(f, " * kf_bp2[5]     single 2nd-order band-pass, f0 = %.0f Hz, B = %.0f Hz\n", F0, BW2);
    fprintf(f, " * kf_bp2_q14[5] same in Q2.14\n */\n");
    fprintf(f, "#ifndef KNOCK_FILTER_H\n#define KNOCK_FILTER_H\n#include <stdint.h>\n\n");
    fprintf(f, "#define KF_FS_HZ %.0f\n#define KF_FIR_N %d\n#define KF_NSEC %d\n\n", FS, N, ns);
    fprintf(f, "static const float kf_fir[KF_FIR_N] = {\n");
    for (n = 0; n < N; n++)
        fprintf(f, "%s%.9ef%s", n % 4 == 0 ? "    " : " ", h[n],
                n == N - 1 ? "\n" : (n % 4 == 3 ? ",\n" : ","));
    fprintf(f, "};\n\nstatic const int16_t kf_fir_q15[KF_FIR_N] = {\n");
    for (n = 0; n < N; n++)
        fprintf(f, "%s%6d%s", n % 10 == 0 ? "    " : " ", q15(h[n]),
                n == N - 1 ? "\n" : (n % 10 == 9 ? ",\n" : ","));
    fprintf(f, "};\n\nstatic const float kf_sos[KF_NSEC][5] = {\n");
    for (k = 0; k < ns; k++) write_biquad(f, &sos[k], k == ns - 1, 0);
    fprintf(f, "};\n\nstatic const int16_t kf_sos_q14[KF_NSEC][5] = {\n");
    for (k = 0; k < ns; k++) write_biquad(f, &sos[k], k == ns - 1, 1);
    fprintf(f, "};\n\nstatic const float kf_bp2[5] =\n");
    write_biquad(f, bp2, 1, 0);
    fprintf(f, ";\n\nstatic const int16_t kf_bp2_q14[5] =\n");
    write_biquad(f, bp2, 1, 1);
    fprintf(f, ";\n\n#endif /* KNOCK_FILTER_H */\n");
    fclose(f);
    return 0;
}

int main(void)
{
    static double h[1024], hw[1024], m1[NF], m2[NF];
    biquad_t sos[FD_MAXSEC], bp2, bp2b;
    double lam, pmin, pmax, smax, beta;
    int w, N, n, ns, k;

    printf("Knock band-pass: fs=%.0f Hz, pass %.0f..%.0f Hz (<=%.0f dB), "
           "stop <=%.0f / >=%.0f Hz (>=%.0f dB)\n\n", FS, FP1, FP2, AP, FST1, FST2, AS);

    /* ---------------- (a) FIR, window method ---------------------- */
    printf("(a) FIR window design, cut-offs %.0f / %.0f Hz (centre of transition bands)\n",
           0.5 * (FST1 + FP1), 0.5 * (FP2 + FST2));
    beta = fd_kaiser_beta(AS);
    printf("    Kaiser formula: beta = %.3f, N = %d taps\n", beta,
           fd_kaiser_length(AS, FP1 - FST1, FS));
    printf("    window     N   pass min/max (dB)   stop max (dB)  | min. N meeting spec\n");
    for (w = 0; w < WIN_COUNT; w++) {
        int Nmin = -1;
        fd_fir_bandpass(hw, FIR_N, 0.5 * (FST1 + FP1), 0.5 * (FP2 + FST2), FS, w, beta);
        check_fir(hw, FIR_N, &pmin, &pmax, &smax);
        for (N = 11; N <= 201 && Nmin < 0; N += 2) {
            double a, b, c;
            fd_fir_bandpass(h, N, 0.5 * (FST1 + FP1), 0.5 * (FP2 + FST2), FS, w, beta);
            check_fir(h, N, &a, &b, &c);
            if (a >= -AP && b <= AP && c <= -AS) Nmin = N;
        }
        printf("    %-8s  %3d   %7.3f / %6.3f      %7.1f        | ", fd_win_name[w],
               FIR_N, pmin, pmax, smax);
        if (Nmin > 0) printf("%d\n", Nmin); else printf("> 201\n");
    }
    fd_fir_bandpass(h, FIR_N, 0.5 * (FST1 + FP1), 0.5 * (FP2 + FST2), FS, WIN_HAMMING, 0.0);
    printf("    chosen: Hamming, N = %d, group delay %.1f samples = %.2f ms, "
           "%d MAC/sample\n\n", FIR_N, 0.5 * (FIR_N - 1), 0.5 * (FIR_N - 1) / FS * 1e3, FIR_N);

    /* ---------------- (b) IIR Butterworth band-pass ---------------- */
    n = fd_butter_bp_order(FP1, FP2, FST1, FST2, AP, AS, FS, &lam);
    printf("(b) Butterworth band-pass: prototype stop-band frequency lambda_s = %.3f\n", lam);
    printf("    required prototype order n = %d  ->  band-pass order %d, %d biquads\n",
           n, 2 * n, n);
    ns = fd_butter_bandpass(sos, n, FP1, FP2, AP, FS);
    printf("    sec       b0          b1          b2          a1          a2      "
           "  |p|     f_p (Hz)  Q\n");
    for (k = 0; k < ns; k++) {
        cplx p1, p2;
        double r, fp, Q;
        fd_biquad_poles(&sos[k], &p1, &p2);
        r = c_abs(p1);
        fp = atan2(p1.im, p1.re) / (2.0 * M_PI) * FS;
        Q = (atan2(p1.im, p1.re)) / (2.0 * (1.0 - r));   /* approx. Q = theta/(2(1-r)) */
        printf("    %d  %11.8f %11.8f %11.8f %11.8f %11.8f  %.5f  %7.1f  %5.1f\n", k,
               sos[k].b[0], sos[k].b[1], sos[k].b[2], sos[k].a[1], sos[k].a[2], r, fp, Q);
    }
    check_sos(sos, ns, &pmin, &pmax, &smax);
    printf("    check: pass band %.3f..%.3f dB, stop band max %.1f dB  -> %s\n",
           pmin, pmax, smax, (pmin >= -AP - 1e-6 && smax <= -AS) ? "spec met" : "NOT met");
    printf("    gain at 8 kHz (valve): FIR %.1f dB, IIR %.1f dB; at 10.5 kHz: FIR %.1f dB, IIR %.1f dB\n",
           fd_db(c_abs(fd_fir_resp(h, FIR_N, 8000.0, FS))), fd_db(c_abs(fd_sos_resp(sos, ns, 8000.0, FS))),
           fd_db(c_abs(fd_fir_resp(h, FIR_N, 10500.0, FS))), fd_db(c_abs(fd_sos_resp(sos, ns, 10500.0, FS))));
    printf("    group delay at %.0f Hz: IIR %.1f samples (%.2f ms), FIR %.1f samples\n",
           F0, fd_sos_grpdelay(sos, ns, F0, FS), fd_sos_grpdelay(sos, ns, F0, FS) / FS * 1e3,
           0.5 * (FIR_N - 1));
    printf("    cost: %d multiplications/sample (direct form I/II), %d state variables\n\n",
           5 * ns, 2 * ns);

    /* ---------------- (c) single biquad ---------------------------- */
    fd_bp2(&bp2, F0, BW2, FS);
    fd_bp2(&bp2b, F0, 1000.0, FS);
    printf("(c) 2nd-order band-pass (bilinear, pre-warped)\n");
    {
        biquad_t *bb[2]; double Bs[2]; int i;
        bb[0] = &bp2; bb[1] = &bp2b; Bs[0] = BW2; Bs[1] = 1000.0;
        for (i = 0; i < 2; i++) {
            cplx p1, p2;
            fd_biquad_poles(bb[i], &p1, &p2);
            printf("    B=%4.0f Hz: b0=%.6f b2=%.6f a1=%.6f a2=%.6f |p|=%.5f f_p=%.1f Hz\n"
                   "              gain 6.5k %.2f dB, 8k %.1f dB, 10.5k %.1f dB, 1k %.1f dB, "
                   "group delay %.1f samples\n",
                   Bs[i], bb[i]->b[0], bb[i]->b[2], bb[i]->a[1], bb[i]->a[2], c_abs(p1),
                   atan2(p1.im, p1.re) / (2 * M_PI) * FS,
                   fd_db(c_abs(fd_sos_resp(bb[i], 1, 6500, FS))), fd_db(c_abs(fd_sos_resp(bb[i], 1, 8000, FS))),
                   fd_db(c_abs(fd_sos_resp(bb[i], 1, 10500, FS))), fd_db(c_abs(fd_sos_resp(bb[i], 1, 1000, FS))),
                   fd_sos_grpdelay(bb[i], 1, F0, FS));
        }
    }

    /* ---------------- plots -------------------------------------- */
    for (k = 0; k < NF; k++) {
        double f = 0.5 * FS * k / (NF - 1);
        m1[k] = fd_db(c_abs(fd_fir_resp(h, FIR_N, f, FS)));
        m2[k] = fd_db(c_abs(fd_sos_resp(sos, ns, f, FS)));
        if (m1[k] < -80) m1[k] = -80;
        if (m2[k] < -80) m2[k] = -80;
    }
    printf("\n");
    ap_plot2(m1, m2, NF, "|H| in dB, 0..12.5 kHz: '*' FIR Hamming N=83, 'o' IIR Butterworth");

    if (export_header("knock_filter.h", h, FIR_N, sos, ns, &bp2) == 0)
        printf("wrote knock_filter.h\n");
    return 0;
}
